# Generated by Django 4.0.1 on 2022-01-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contet',
            new_name='content',
        ),
    ]
